server:
  port: 9000

app:
  issuer: ${APP_ISSUER:http://localhost:9000}
  cors:
    origins: ${APP_CORS_ORIGINS:http://localhost:5173}

spring:
  application:
    name: gera-auth-server
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sas}
    username: ${SPRING_DATASOURCE_USERNAME:sas}
    password: ${SPRING_DATASOURCE_PASSWORD:sas}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
